export interface Event {
  id: string
  title: string
  description: string
  longDescription?: string
  eventDate: string
  time: string
  location: string
  address: string
  region: string
  price: string
  category: string
  status: 'draft' | 'pending' | 'published' | 'cancelled'
  image: string
  gallery?: string[]
  organizerId: string
  organizerName: string
  organizerLogo?: string
  attendees: number
  maxAttendees?: number
  revenue: number
  expenses: number
  profit: number
  featured: boolean
  rating?: number
  reviewCount?: number
}

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Addis Tech Summit 2024',
    description: 'Join Ethiopia\'s largest technology conference featuring keynotes, workshops, and networking opportunities.',
    longDescription: 'The Addis Tech Summit 2024 is Ethiopia\'s premier technology conference bringing together innovators, entrepreneurs, and tech enthusiasts. Experience keynote speeches from industry leaders, hands-on workshops, and extensive networking opportunities.',
    eventDate: '2024-06-15',
    time: '9:00 AM - 6:00 PM',
    location: 'Millennium Hall',
    address: 'Millennium Hall, Bole Road',
    region: 'Addis Ababa',
    price: 'ETB 500 - 1,500',
    category: 'Conference',
    status: 'published',
    image: '/assets/image (24).jpg',
    gallery: ['/assets/image (1).jpg', '/assets/image (2).jpg', '/assets/image (3).jpg'],
    organizerId: 'org_001',
    organizerName: 'Tech Association',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 320,
    maxAttendees: 500,
    revenue: 384000,
    expenses: 150000,
    profit: 234000,
    featured: true,
    rating: 4.8,
    reviewCount: 145,
  },
  {
    id: '2',
    title: 'Ethiopian Coffee Festival',
    description: 'Celebrate Ethiopia\'s coffee heritage with tastings, workshops, and cultural performances.',
    longDescription: 'Immerse yourself in the rich tradition of Ethiopian coffee culture. This festival features coffee tastings from various regions, traditional coffee ceremonies, barista workshops, and live cultural performances.',
    eventDate: '2024-05-22',
    time: '10:00 AM - 8:00 PM',
    location: 'Friendship Park',
    address: 'Friendship Park, Bole',
    region: 'Addis Ababa',
    price: 'ETB 300',
    category: 'Festival',
    status: 'published',
    image: '/assets/image (4).jpg',
    gallery: ['/assets/image (5).jpg', '/assets/image (6).jpg'],
    organizerId: 'org_002',
    organizerName: 'Coffee Exporters',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 185,
    maxAttendees: 300,
    revenue: 55500,
    expenses: 25000,
    profit: 30500,
    featured: true,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: '3',
    title: 'Cultural Heritage Exhibition',
    description: 'Explore Ethiopia\'s rich cultural heritage through art, artifacts, and interactive displays.',
    longDescription: 'A comprehensive exhibition showcasing Ethiopia\'s diverse cultural heritage, featuring ancient artifacts, contemporary art, traditional crafts, and interactive displays that bring history to life.',
    eventDate: '2024-05-28',
    time: '11:00 AM - 7:00 PM',
    location: 'National Museum',
    address: 'National Museum, King George VI Street',
    region: 'Addis Ababa',
    price: 'ETB 200',
    category: 'Exhibition',
    status: 'published',
    image: '/assets/hero-first.jpg',
    gallery: ['/assets/image (7).jpg', '/assets/image (8).jpg'],
    organizerId: 'org_003',
    organizerName: 'National Museum',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 156,
    maxAttendees: 200,
    revenue: 31200,
    expenses: 12000,
    profit: 19200,
    featured: true,
    rating: 4.7,
    reviewCount: 62,
  },
  {
    id: '4',
    title: 'Business Networking Mixer',
    description: 'Connect with business leaders and entrepreneurs in an exclusive networking environment.',
    longDescription: 'An exclusive evening networking event designed for business professionals, entrepreneurs, and investors. Features keynote speeches, breakout sessions, and ample networking opportunities.',
    eventDate: '2024-06-05',
    time: '6:00 PM - 10:00 PM',
    location: 'Hyatt Regency',
    address: 'Hyatt Regency, Meskel Square',
    region: 'Addis Ababa',
    price: 'ETB 800',
    category: 'Networking',
    status: 'published',
    image: '/assets/image (8).jpg',
    gallery: ['/assets/image (9).jpg', '/assets/image (10).jpg'],
    organizerId: 'org_004',
    organizerName: 'Addis Chamber',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 95,
    maxAttendees: 150,
    revenue: 76000,
    expenses: 35000,
    profit: 41000,
    featured: true,
    rating: 4.5,
    reviewCount: 38,
  },
  {
    id: '5',
    title: 'Music Festival 2024',
    description: 'Experience live performances from top Ethiopian and international artists.',
    longDescription: 'A spectacular music festival featuring performances from renowned Ethiopian artists and international acts. Multiple stages, food vendors, and an unforgettable atmosphere.',
    eventDate: '2024-07-10',
    time: '4:00 PM - 11:00 PM',
    location: 'Meskel Square',
    address: 'Meskel Square, Addis Ababa',
    region: 'Addis Ababa',
    price: 'ETB 400 - 1,000',
    category: 'Music',
    status: 'published',
    image: '/assets/image (9).jpg',
    gallery: ['/assets/image (11).jpg', '/assets/image (12).jpg'],
    organizerId: 'org_005',
    organizerName: 'Abyssinia Events',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 542,
    maxAttendees: 1000,
    revenue: 378000,
    expenses: 180000,
    profit: 198000,
    featured: true,
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: '6',
    title: 'Startup Pitch Competition',
    description: 'Watch innovative startups pitch their ideas to investors and win funding.',
    longDescription: 'An exciting startup pitch competition where emerging entrepreneurs present their innovative business ideas to a panel of experienced investors and industry experts.',
    eventDate: '2024-06-20',
    time: '2:00 PM - 7:00 PM',
    location: 'iceaddis',
    address: 'iceaddis Innovation Hub, Bole',
    region: 'Addis Ababa',
    price: 'Free',
    category: 'Business',
    status: 'published',
    image: '/assets/image (10).jpg',
    gallery: ['/assets/image (13).jpg', '/assets/image (14).jpg'],
    organizerId: 'org_006',
    organizerName: 'iceaddis',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 78,
    maxAttendees: 100,
    revenue: 0,
    expenses: 8000,
    profit: -8000,
    featured: false,
    rating: 4.4,
    reviewCount: 28,
  },
  {
    id: '7',
    title: 'Digital Marketing Workshop',
    description: 'Learn the latest digital marketing strategies and tools from industry experts.',
    longDescription: 'A comprehensive workshop covering SEO, social media marketing, content strategy, and analytics. Perfect for marketers looking to enhance their digital skills.',
    eventDate: '2024-06-08',
    time: '9:00 AM - 5:00 PM',
    location: 'Sheraton Addis',
    address: 'Sheraton Addis, Taitu Street',
    region: 'Addis Ababa',
    price: 'ETB 600',
    category: 'Workshop',
    status: 'published',
    image: '/assets/image (15).jpg',
    gallery: ['/assets/image (16).jpg', '/assets/image (17).jpg'],
    organizerId: 'org_001',
    organizerName: 'Tech Association',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 45,
    maxAttendees: 60,
    revenue: 27000,
    expenses: 15000,
    profit: 12000,
    featured: false,
    rating: 4.6,
    reviewCount: 22,
  },
  {
    id: '8',
    title: 'Ethiopian Fashion Week',
    description: 'Showcase of Ethiopian fashion designers and traditional clothing with modern twists.',
    longDescription: 'Experience the vibrant world of Ethiopian fashion with runway shows, designer exhibitions, and networking events. Celebrating both traditional and contemporary Ethiopian fashion.',
    eventDate: '2024-07-15',
    time: '5:00 PM - 10:00 PM',
    location: 'Skylight Hotel',
    address: 'Skylight Hotel, Bole',
    region: 'Addis Ababa',
    price: 'ETB 700 - 2,000',
    category: 'Fashion',
    status: 'published',
    image: '/assets/image (18).jpg',
    gallery: ['/assets/image (19).jpg', '/assets/image (20).jpg'],
    organizerId: 'org_007',
    organizerName: 'Fashion Ethiopia',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 210,
    maxAttendees: 300,
    revenue: 294000,
    expenses: 120000,
    profit: 174000,
    featured: true,
    rating: 4.7,
    reviewCount: 98,
  },
  {
    id: '9',
    title: 'Food & Wine Tasting',
    description: 'Discover Ethiopian cuisine paired with fine wines from around the world.',
    longDescription: 'An elegant evening of food and wine pairing featuring traditional Ethiopian dishes and international wines. Expert sommeliers will guide you through each pairing.',
    eventDate: '2024-06-25',
    time: '7:00 PM - 11:00 PM',
    location: 'Radisson Blu',
    address: 'Radisson Blu, Kazanchis',
    region: 'Addis Ababa',
    price: 'ETB 1,200',
    category: 'Food',
    status: 'published',
    image: '/assets/image (21).jpg',
    gallery: ['/assets/image (22).jpg', '/assets/image (23).jpg'],
    organizerId: 'org_008',
    organizerName: 'Culinary Arts ET',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 65,
    maxAttendees: 80,
    revenue: 78000,
    expenses: 45000,
    profit: 33000,
    featured: false,
    rating: 4.8,
    reviewCount: 34,
  },
  {
    id: '10',
    title: 'Addis Marathon 2024',
    description: 'Join thousands of runners in Ethiopia\'s biggest marathon event.',
    longDescription: 'The annual Addis Marathon features 5K, 10K, half marathon, and full marathon categories. All proceeds go to local charities supporting education and healthcare.',
    eventDate: '2024-08-10',
    time: '6:00 AM - 12:00 PM',
    location: 'Meskel Square',
    address: 'Starting at Meskel Square',
    region: 'Addis Ababa',
    price: 'ETB 200 - 500',
    category: 'Sports',
    status: 'published',
    image: '/assets/image (24).jpg',
    gallery: ['/assets/image (25).jpg', '/assets/image (26).jpg'],
    organizerId: 'org_009',
    organizerName: 'Athletics Federation',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 1250,
    maxAttendees: 2000,
    revenue: 437500,
    expenses: 200000,
    profit: 237500,
    featured: true,
    rating: 4.9,
    reviewCount: 456,
  },
  {
    id: '11',
    title: 'AI & Machine Learning Summit',
    description: 'Explore the future of AI and machine learning with leading experts.',
    longDescription: 'A two-day summit featuring workshops, presentations, and panel discussions on artificial intelligence, machine learning, and their applications in various industries.',
    eventDate: '2024-09-05',
    time: '9:00 AM - 6:00 PM',
    location: 'Hilton Addis',
    address: 'Hilton Addis Ababa, Menelik II Avenue',
    region: 'Addis Ababa',
    price: 'ETB 1,000 - 2,500',
    category: 'Conference',
    status: 'published',
    image: '/assets/image (27).jpg',
    gallery: ['/assets/image (28).jpg', '/assets/image (29).jpg'],
    organizerId: 'org_001',
    organizerName: 'Tech Association',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 280,
    maxAttendees: 400,
    revenue: 476000,
    expenses: 220000,
    profit: 256000,
    featured: true,
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: '12',
    title: 'Photography Exhibition',
    description: 'Stunning photography showcasing Ethiopia\'s landscapes and people.',
    longDescription: 'A curated exhibition of photographs by local and international photographers, capturing the beauty, diversity, and spirit of Ethiopia.',
    eventDate: '2024-06-18',
    time: '10:00 AM - 8:00 PM',
    location: 'Alliance Ethio-Française',
    address: 'Alliance Ethio-Française, Arat Kilo',
    region: 'Addis Ababa',
    price: 'ETB 100',
    category: 'Exhibition',
    status: 'published',
    image: '/assets/image (30).jpg',
    gallery: ['/assets/image (1).jpg', '/assets/image (2).jpg'],
    organizerId: 'org_010',
    organizerName: 'Photo Society ET',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 89,
    maxAttendees: 150,
    revenue: 8900,
    expenses: 5000,
    profit: 3900,
    featured: false,
    rating: 4.5,
    reviewCount: 41,
  },
  {
    id: '13',
    title: 'Blockchain & Cryptocurrency Forum',
    description: 'Understanding blockchain technology and cryptocurrency in Africa.',
    longDescription: 'An educational forum discussing blockchain technology, cryptocurrency adoption, and their potential impact on African economies and businesses.',
    eventDate: '2024-07-22',
    time: '1:00 PM - 6:00 PM',
    location: 'Capital Hotel',
    address: 'Capital Hotel & Spa, Mexico Square',
    region: 'Addis Ababa',
    price: 'ETB 750',
    category: 'Conference',
    status: 'published',
    image: '/assets/image (3).jpg',
    gallery: ['/assets/image (4).jpg', '/assets/image (5).jpg'],
    organizerId: 'org_011',
    organizerName: 'Crypto Africa',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 112,
    maxAttendees: 180,
    revenue: 84000,
    expenses: 40000,
    profit: 44000,
    featured: false,
    rating: 4.3,
    reviewCount: 52,
  },
  {
    id: '14',
    title: 'Jazz Night Under the Stars',
    description: 'An evening of smooth jazz music in an outdoor setting.',
    longDescription: 'Enjoy live jazz performances from local and international artists in a beautiful outdoor venue. Bring your friends and family for a memorable evening.',
    eventDate: '2024-06-30',
    time: '7:00 PM - 11:00 PM',
    location: 'Ghion Hotel Gardens',
    address: 'Ghion Hotel, Ras Desta Damtew Avenue',
    region: 'Addis Ababa',
    price: 'ETB 350',
    category: 'Music',
    status: 'published',
    image: '/assets/image (6).jpg',
    gallery: ['/assets/image (7).jpg', '/assets/image (8).jpg'],
    organizerId: 'org_005',
    organizerName: 'Abyssinia Events',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 156,
    maxAttendees: 200,
    revenue: 54600,
    expenses: 28000,
    profit: 26600,
    featured: false,
    rating: 4.7,
    reviewCount: 78,
  },
  {
    id: '15',
    title: 'Women in Tech Conference',
    description: 'Empowering women in technology through networking and mentorship.',
    longDescription: 'A conference dedicated to supporting and empowering women in the technology sector. Features inspiring speakers, workshops, and networking opportunities.',
    eventDate: '2024-08-15',
    time: '9:00 AM - 5:00 PM',
    location: 'Marriott Executive Apartments',
    address: 'Marriott Executive Apartments, Bole',
    region: 'Addis Ababa',
    price: 'ETB 400',
    category: 'Conference',
    status: 'published',
    image: '/assets/image (9).jpg',
    gallery: ['/assets/image (10).jpg', '/assets/image (11).jpg'],
    organizerId: 'org_012',
    organizerName: 'Women Tech ET',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 178,
    maxAttendees: 250,
    revenue: 71200,
    expenses: 35000,
    profit: 36200,
    featured: true,
    rating: 4.9,
    reviewCount: 123,
  },
  {
    id: '16',
    title: 'Traditional Music Festival',
    description: 'Celebrate Ethiopian traditional music and dance.',
    longDescription: 'A vibrant festival showcasing traditional Ethiopian music and dance from different regions. Experience the rich cultural diversity of Ethiopia.',
    eventDate: '2024-07-05',
    time: '3:00 PM - 9:00 PM',
    location: 'Addis Ababa Stadium',
    address: 'Addis Ababa Stadium, Janmeda',
    region: 'Addis Ababa',
    price: 'ETB 250',
    category: 'Festival',
    status: 'published',
    image: '/assets/image (12).jpg',
    gallery: ['/assets/image (13).jpg', '/assets/image (14).jpg'],
    organizerId: 'org_013',
    organizerName: 'Cultural Heritage Org',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 425,
    maxAttendees: 600,
    revenue: 106250,
    expenses: 55000,
    profit: 51250,
    featured: false,
    rating: 4.6,
    reviewCount: 189,
  },
  {
    id: '17',
    title: 'Yoga & Wellness Retreat',
    description: 'A weekend retreat focused on yoga, meditation, and holistic wellness.',
    longDescription: 'Escape the city for a rejuvenating weekend of yoga, meditation, healthy eating, and wellness workshops. Perfect for beginners and experienced practitioners.',
    eventDate: '2024-08-20',
    time: '8:00 AM - 6:00 PM',
    location: 'Debre Zeit Resort',
    address: 'Debre Zeit Lakeside Resort',
    region: 'Oromia',
    price: 'ETB 1,500',
    category: 'Wellness',
    status: 'published',
    image: '/assets/image (15).jpg',
    gallery: ['/assets/image (16).jpg', '/assets/image (17).jpg'],
    organizerId: 'org_014',
    organizerName: 'Wellness Ethiopia',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 42,
    maxAttendees: 50,
    revenue: 63000,
    expenses: 35000,
    profit: 28000,
    featured: false,
    rating: 4.8,
    reviewCount: 31,
  },
  {
    id: '18',
    title: 'E-Commerce Summit',
    description: 'Learn how to build and scale your online business in Ethiopia.',
    longDescription: 'A comprehensive summit covering e-commerce strategies, digital payments, logistics, and marketing. Featuring successful Ethiopian e-commerce entrepreneurs.',
    eventDate: '2024-09-12',
    time: '9:00 AM - 5:00 PM',
    location: 'Jupiter International Hotel',
    address: 'Jupiter International Hotel, Bole',
    region: 'Addis Ababa',
    price: 'ETB 650',
    category: 'Business',
    status: 'published',
    image: '/assets/image (18).jpg',
    gallery: ['/assets/image (19).jpg', '/assets/image (20).jpg'],
    organizerId: 'org_004',
    organizerName: 'Addis Chamber',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 134,
    maxAttendees: 200,
    revenue: 87100,
    expenses: 42000,
    profit: 45100,
    featured: false,
    rating: 4.5,
    reviewCount: 67,
  },
  {
    id: '19',
    title: 'Film Festival Ethiopia',
    description: 'Showcasing the best of Ethiopian and African cinema.',
    longDescription: 'A week-long film festival featuring Ethiopian and African films, documentaries, and short films. Includes Q&A sessions with filmmakers and industry panels.',
    eventDate: '2024-10-01',
    time: '6:00 PM - 10:00 PM',
    location: 'Ethiopian National Theatre',
    address: 'Ethiopian National Theatre, Ras Mekonnen Avenue',
    region: 'Addis Ababa',
    price: 'ETB 150 - 400',
    category: 'Entertainment',
    status: 'published',
    image: '/assets/image (21).jpg',
    gallery: ['/assets/image (22).jpg', '/assets/image (23).jpg'],
    organizerId: 'org_015',
    organizerName: 'Film Society ET',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 267,
    maxAttendees: 350,
    revenue: 66750,
    expenses: 38000,
    profit: 28750,
    featured: false,
    rating: 4.7,
    reviewCount: 142,
  },
  {
    id: '20',
    title: 'Renewable Energy Conference',
    description: 'Exploring sustainable energy solutions for Ethiopia.',
    longDescription: 'A conference bringing together experts, policymakers, and businesses to discuss renewable energy opportunities and challenges in Ethiopia.',
    eventDate: '2024-09-25',
    time: '9:00 AM - 6:00 PM',
    location: 'UN Conference Center',
    address: 'UN Conference Center, Africa Avenue',
    region: 'Addis Ababa',
    price: 'ETB 900',
    category: 'Conference',
    status: 'published',
    image: '/assets/image (24).jpg',
    gallery: ['/assets/image (25).jpg', '/assets/image (26).jpg'],
    organizerId: 'org_016',
    organizerName: 'Green Energy ET',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 198,
    maxAttendees: 280,
    revenue: 178200,
    expenses: 95000,
    profit: 83200,
    featured: true,
    rating: 4.6,
    reviewCount: 94,
  },
  {
    id: '21',
    title: 'Kids Science Fair',
    description: 'Inspiring young minds through hands-on science activities.',
    longDescription: 'An interactive science fair for children featuring experiments, demonstrations, and workshops designed to spark curiosity and love for science.',
    eventDate: '2024-07-28',
    time: '10:00 AM - 4:00 PM',
    location: 'Science Museum',
    address: 'Ethiopian Science Museum, Churchill Avenue',
    region: 'Addis Ababa',
    price: 'ETB 50',
    category: 'Education',
    status: 'published',
    image: '/assets/image (27).jpg',
    gallery: ['/assets/image (28).jpg', '/assets/image (29).jpg'],
    organizerId: 'org_017',
    organizerName: 'Science for Kids',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 312,
    maxAttendees: 400,
    revenue: 15600,
    expenses: 12000,
    profit: 3600,
    featured: false,
    rating: 4.9,
    reviewCount: 178,
  },
  {
    id: '22',
    title: 'Real Estate Investment Forum',
    description: 'Opportunities and trends in Ethiopian real estate market.',
    longDescription: 'A forum for investors, developers, and industry professionals to discuss real estate investment opportunities, market trends, and regulatory updates.',
    eventDate: '2024-08-05',
    time: '2:00 PM - 7:00 PM',
    location: 'Elilly International Hotel',
    address: 'Elilly International Hotel, Bole',
    region: 'Addis Ababa',
    price: 'ETB 1,000',
    category: 'Business',
    status: 'published',
    image: '/assets/image (30).jpg',
    gallery: ['/assets/image (1).jpg', '/assets/image (2).jpg'],
    organizerId: 'org_018',
    organizerName: 'Real Estate Council',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 156,
    maxAttendees: 220,
    revenue: 156000,
    expenses: 68000,
    profit: 88000,
    featured: false,
    rating: 4.4,
    reviewCount: 73,
  },
  {
    id: '23',
    title: 'Book Fair Addis',
    description: 'Celebrating literature and reading culture in Ethiopia.',
    longDescription: 'An annual book fair featuring local and international publishers, author signings, reading sessions, and literary discussions.',
    eventDate: '2024-09-15',
    time: '9:00 AM - 7:00 PM',
    location: 'Millennium Hall',
    address: 'Millennium Hall, Bole Road',
    region: 'Addis Ababa',
    price: 'Free',
    category: 'Cultural',
    status: 'published',
    image: '/assets/image (3).jpg',
    gallery: ['/assets/image (4).jpg', '/assets/image (5).jpg'],
    organizerId: 'org_019',
    organizerName: 'Publishers Association',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 523,
    maxAttendees: 800,
    revenue: 0,
    expenses: 45000,
    profit: -45000,
    featured: false,
    rating: 4.7,
    reviewCount: 245,
  },
  {
    id: '24',
    title: 'Mobile App Development Bootcamp',
    description: 'Learn to build mobile apps from scratch in this intensive bootcamp.',
    longDescription: 'A 3-day intensive bootcamp covering iOS and Android app development. Includes hands-on projects and mentorship from experienced developers.',
    eventDate: '2024-07-18',
    time: '9:00 AM - 6:00 PM',
    location: 'iceaddis',
    address: 'iceaddis Innovation Hub, Bole',
    region: 'Addis Ababa',
    price: 'ETB 2,500',
    category: 'Workshop',
    status: 'published',
    image: '/assets/image (6).jpg',
    gallery: ['/assets/image (7).jpg', '/assets/image (8).jpg'],
    organizerId: 'org_006',
    organizerName: 'iceaddis',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 28,
    maxAttendees: 30,
    revenue: 70000,
    expenses: 35000,
    profit: 35000,
    featured: false,
    rating: 4.8,
    reviewCount: 24,
  },
  {
    id: '25',
    title: 'Art & Craft Market',
    description: 'Discover unique handmade crafts and artwork from local artisans.',
    longDescription: 'A vibrant marketplace featuring handmade crafts, paintings, jewelry, and traditional Ethiopian art. Support local artisans and find unique pieces.',
    eventDate: '2024-06-22',
    time: '10:00 AM - 6:00 PM',
    location: 'Shola Market',
    address: 'Shola Market, Old Airport Area',
    region: 'Addis Ababa',
    price: 'Free',
    category: 'Cultural',
    status: 'published',
    image: '/assets/image (9).jpg',
    gallery: ['/assets/image (10).jpg', '/assets/image (11).jpg'],
    organizerId: 'org_020',
    organizerName: 'Artisans Collective',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 387,
    maxAttendees: 500,
    revenue: 0,
    expenses: 8000,
    profit: -8000,
    featured: false,
    rating: 4.5,
    reviewCount: 156,
  },
  {
    id: '26',
    title: 'Cybersecurity Workshop',
    description: 'Protect your business from cyber threats with expert guidance.',
    longDescription: 'A practical workshop on cybersecurity best practices, threat detection, and incident response. Essential for IT professionals and business owners.',
    eventDate: '2024-08-28',
    time: '9:00 AM - 5:00 PM',
    location: 'Sheraton Addis',
    address: 'Sheraton Addis, Taitu Street',
    region: 'Addis Ababa',
    price: 'ETB 850',
    category: 'Workshop',
    status: 'published',
    image: '/assets/image (12).jpg',
    gallery: ['/assets/image (13).jpg', '/assets/image (14).jpg'],
    organizerId: 'org_001',
    organizerName: 'Tech Association',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 67,
    maxAttendees: 80,
    revenue: 56950,
    expenses: 28000,
    profit: 28950,
    featured: false,
    rating: 4.7,
    reviewCount: 42,
  },
  {
    id: '27',
    title: 'Comedy Night Live',
    description: 'Laugh out loud with Ethiopia\'s funniest comedians.',
    longDescription: 'An evening of stand-up comedy featuring top Ethiopian comedians. Enjoy food, drinks, and non-stop laughter.',
    eventDate: '2024-07-12',
    time: '8:00 PM - 11:00 PM',
    location: 'Gaslight Night Club',
    address: 'Gaslight, Bole Road',
    region: 'Addis Ababa',
    price: 'ETB 300',
    category: 'Entertainment',
    status: 'published',
    image: '/assets/image (15).jpg',
    gallery: ['/assets/image (16).jpg', '/assets/image (17).jpg'],
    organizerId: 'org_021',
    organizerName: 'Comedy Central ET',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 142,
    maxAttendees: 180,
    revenue: 42600,
    expenses: 22000,
    profit: 20600,
    featured: false,
    rating: 4.6,
    reviewCount: 87,
  },
  {
    id: '28',
    title: 'Agriculture Innovation Summit',
    description: 'Modern farming techniques and agritech solutions for Ethiopia.',
    longDescription: 'A summit focused on agricultural innovation, featuring presentations on modern farming techniques, agritech startups, and sustainable agriculture practices.',
    eventDate: '2024-09-20',
    time: '9:00 AM - 6:00 PM',
    location: 'Skylight Hotel',
    address: 'Skylight Hotel, Bole',
    region: 'Addis Ababa',
    price: 'ETB 700',
    category: 'Conference',
    status: 'published',
    image: '/assets/image (18).jpg',
    gallery: ['/assets/image (19).jpg', '/assets/image (20).jpg'],
    organizerId: 'org_022',
    organizerName: 'AgriTech Ethiopia',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 189,
    maxAttendees: 250,
    revenue: 132300,
    expenses: 72000,
    profit: 60300,
    featured: false,
    rating: 4.5,
    reviewCount: 91,
  },
  {
    id: '29',
    title: 'Classical Music Concert',
    description: 'An evening of classical music performed by the National Orchestra.',
    longDescription: 'Experience the beauty of classical music with performances of works by Ethiopian and international composers, performed by the Ethiopian National Orchestra.',
    eventDate: '2024-08-18',
    time: '7:00 PM - 10:00 PM',
    location: 'Ethiopian National Theatre',
    address: 'Ethiopian National Theatre, Ras Mekonnen Avenue',
    region: 'Addis Ababa',
    price: 'ETB 250 - 600',
    category: 'Music',
    status: 'published',
    image: '/assets/image (21).jpg',
    gallery: ['/assets/image (22).jpg', '/assets/image (23).jpg'],
    organizerId: 'org_023',
    organizerName: 'National Orchestra',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 234,
    maxAttendees: 300,
    revenue: 93600,
    expenses: 48000,
    profit: 45600,
    featured: false,
    rating: 4.8,
    reviewCount: 128,
  },
  {
    id: '30',
    title: 'Gaming Tournament 2024',
    description: 'Compete in Ethiopia\'s biggest e-sports gaming tournament.',
    longDescription: 'A competitive gaming tournament featuring popular games like FIFA, Call of Duty, and League of Legends. Cash prizes for winners and exciting entertainment.',
    eventDate: '2024-10-15',
    time: '10:00 AM - 8:00 PM',
    location: 'Millennium Hall',
    address: 'Millennium Hall, Bole Road',
    region: 'Addis Ababa',
    price: 'ETB 100 - 500',
    category: 'Sports',
    status: 'published',
    image: '/assets/image (24).jpg',
    gallery: ['/assets/image (25).jpg', '/assets/image (26).jpg'],
    organizerId: 'org_024',
    organizerName: 'E-Sports Ethiopia',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 456,
    maxAttendees: 600,
    revenue: 136800,
    expenses: 85000,
    profit: 51800,
    featured: true,
    rating: 4.7,
    reviewCount: 234,
  },
  {
    id: '31',
    title: 'Health & Wellness Expo',
    description: 'Discover the latest in health, fitness, and wellness products.',
    longDescription: 'An expo featuring health and wellness products, fitness demonstrations, nutrition workshops, and consultations with health professionals.',
    eventDate: '2024-09-08',
    time: '9:00 AM - 6:00 PM',
    location: 'Millennium Hall',
    address: 'Millennium Hall, Bole Road',
    region: 'Addis Ababa',
    price: 'ETB 150',
    category: 'Exhibition',
    status: 'published',
    image: '/assets/image (27).jpg',
    gallery: ['/assets/image (28).jpg', '/assets/image (29).jpg'],
    organizerId: 'org_014',
    organizerName: 'Wellness Ethiopia',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 298,
    maxAttendees: 400,
    revenue: 44700,
    expenses: 32000,
    profit: 12700,
    featured: false,
    rating: 4.6,
    reviewCount: 145,
  },
  {
    id: '32',
    title: 'Leadership Masterclass',
    description: 'Develop your leadership skills with industry experts.',
    longDescription: 'An intensive masterclass on leadership, management, and team building. Learn from successful Ethiopian business leaders and international experts.',
    eventDate: '2024-10-05',
    time: '9:00 AM - 5:00 PM',
    location: 'Radisson Blu',
    address: 'Radisson Blu, Kazanchis',
    region: 'Addis Ababa',
    price: 'ETB 1,200',
    category: 'Workshop',
    status: 'published',
    image: '/assets/image (30).jpg',
    gallery: ['/assets/image (1).jpg', '/assets/image (2).jpg'],
    organizerId: 'org_025',
    organizerName: 'Leadership Institute',
    organizerLogo: '/assets/placeholder-logo.png',
    attendees: 78,
    maxAttendees: 100,
    revenue: 93600,
    expenses: 48000,
    profit: 45600,
    featured: false,
    rating: 4.9,
    reviewCount: 56,
  },
]

export const getEventById = (id: string): Event | undefined => {
  return mockEvents.find(event => event.id === id)
}

export const getEventsByCategory = (category: string): Event[] => {
  return mockEvents.filter(event => event.category === category)
}

export const getFeaturedEvents = (): Event[] => {
  return mockEvents.filter(event => event.featured)
}

export const getEventsByOrganizer = (organizerId: string): Event[] => {
  return mockEvents.filter(event => event.organizerId === organizerId)
}

export const getUpcomingEvents = (): Event[] => {
  const now = new Date()
  return mockEvents.filter(event => new Date(event.eventDate) > now)
}

export const getPastEvents = (): Event[] => {
  const now = new Date()
  return mockEvents.filter(event => new Date(event.eventDate) <= now)
}
